#!/usr/bin/env bash
# Maintains one schema-validated public Run index and marker-free audit records.
set -euo pipefail
marker='<!-- issue-agent-run-state:active:v1 -->'
safe_failure() { printf '%s\n' '{"outcome":"BLOCKED","safe_summary":"public state comment operation could not be completed"}'; exit 1; }
usage() { printf '%s\n' 'usage: public-state-comment.sh {active-create|active-update|checkpoint|switch} OPTIONS' >&2; exit 2; }
operation=${1:-}; shift || true
case $operation in active-create|active-update|checkpoint|switch) ;; *) usage ;; esac
repository= issue_number= run_id= started_at= updated_at= current_state= state_before_stop= resume_state= role= model= outcome= review_return_count= test_summary= branch= commit= draft_pr= head_sha= ci_summary= stop_or_wait_reason= opaque_checkpoint= safe_summary= redacted_integrity= token_count= cost= event= transition= discard_reason= old_run_id= old_opaque_checkpoint= old_redacted_integrity= old_state= old_safe_summary= old_transition=
while (($#)); do (($# >= 2)) || usage; case $1 in
  --repository) repository=$2;; --issue-number) issue_number=$2;; --run-id) run_id=$2;; --started-at) started_at=$2;; --updated-at) updated_at=$2;; --current-state) current_state=$2;; --state-before-stop) state_before_stop=$2;; --resume-state) resume_state=$2;; --role) role=$2;; --model) model=$2;; --outcome) outcome=$2;; --review-return-count) review_return_count=$2;; --test-summary) test_summary=$2;; --branch) branch=$2;; --commit) commit=$2;; --draft-pr) draft_pr=$2;; --head-sha) head_sha=$2;; --ci-summary) ci_summary=$2;; --stop-or-wait-reason) stop_or_wait_reason=$2;; --opaque-checkpoint) opaque_checkpoint=$2;; --safe-summary) safe_summary=$2;; --redacted-integrity) redacted_integrity=$2;; --token-count) token_count=$2;; --cost) cost=$2;; --event) event=$2;; --transition) transition=$2;; --discard-reason) discard_reason=$2;; --old-run-id) old_run_id=$2;; --old-opaque-checkpoint) old_opaque_checkpoint=$2;; --old-redacted-integrity) old_redacted_integrity=$2;; --old-state) old_state=$2;; --old-safe-summary) old_safe_summary=$2;; --old-transition) old_transition=$2;; *) usage;; esac; shift 2; done
[[ $repository =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ && $issue_number =~ ^[1-9][0-9]*$ ]] || safe_failure
has_control_or_long() { [[ -z $1 || ${#1} -gt 160 || $1 =~ [[:cntrl:]] || $1 == *'<!--'* ]]; }
credential_free() { local lower=${1,,}; [[ ! $lower =~ (ghp_|gho_|ghu_|ghs_|ghr_|github_pat_|akia) ]]; }
safe_text_re='^[A-Za-z0-9][A-Za-z0-9 .,:;()_+=#@-]*$'
safe_text() { local lower=${1,,}; credential_free "$1" && ! has_control_or_long "$1" && [[ $1 =~ $safe_text_re ]] && [[ ! $lower =~ (manifest|patch|log|authorization|bearer|credential|secret|token) ]]; }
opaque() { ! has_control_or_long "$1" && [[ $1 =~ ^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$ ]]; }
state() { [[ $1 == unset || $1 =~ ^[A-Z][A-Z_]{1,63}$ ]]; }; timestamp() { [[ $1 =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]+Z$ ]]; }; run() { [[ $1 =~ ^[a-f0-9]{32,128}$ ]]; }; transition_value() { [[ $1 =~ ^[A-Z][A-Z_]{1,63}\ -\>\ [A-Z][A-Z_]{1,63}$ ]]; }
branch_value() { [[ $1 == unset || ( $1 =~ ^[A-Za-z0-9][A-Za-z0-9._/-]{0,127}$ && $1 != *'..'* && $1 != *'//'*) ]]; }; sha_value() { [[ $1 == unset || $1 =~ ^[a-f0-9]{7,64}$ ]]; }; pr_value() { [[ $1 == unset || $1 =~ ^#[1-9][0-9]*$ ]]; }
validate_active() { for public_value in "$run_id" "$started_at" "$updated_at" "$current_state" "$state_before_stop" "$resume_state" "$role" "$model" "$outcome" "$review_return_count" "$test_summary" "$branch" "$commit" "$draft_pr" "$head_sha" "$ci_summary" "$stop_or_wait_reason" "$opaque_checkpoint" "$safe_summary" "$redacted_integrity" "$token_count" "$cost"; do credential_free "$public_value" || safe_failure; done; run "$run_id" && timestamp "$started_at" && timestamp "$updated_at" && state "$current_state" && state "$state_before_stop" && state "$resume_state" || safe_failure; [[ $role =~ ^[A-Za-z][A-Za-z_-]{1,63}$ && $model =~ ^[A-Za-z0-9._:-]{1,127}$ && $outcome =~ ^[A-Z][A-Z_]{1,63}$ && $review_return_count =~ ^[0-9]+$ ]] || safe_failure; safe_text "$test_summary" && branch_value "$branch" && sha_value "$commit" && pr_value "$draft_pr" && sha_value "$head_sha" && safe_text "$ci_summary" && safe_text "$stop_or_wait_reason" && safe_text "$safe_summary" && opaque "$opaque_checkpoint" && opaque "$redacted_integrity" || safe_failure; [[ -z $token_count || $token_count =~ ^[0-9]+$ ]] && [[ -z $cost || $cost =~ ^[0-9]+([.][0-9]+)?$ ]] || safe_failure; }
active_body() { validate_active; printf '%s\n' "$marker" '## Issue Agent Run State (v1)' "- run_id: $run_id" "- started_at: $started_at" "- updated_at: $updated_at" "- current_state: $current_state" "- state_before_stop: $state_before_stop" "- resume_state: $resume_state" "- role: $role" "- model: $model" "- outcome: $outcome" "- review_return_count: $review_return_count" "- test_summary: $test_summary" "- branch: $branch" "- commit: $commit" "- draft_pr: $draft_pr" "- head_sha: $head_sha" "- ci_summary: $ci_summary" "- stop_or_wait_reason: $stop_or_wait_reason" "- opaque_checkpoint: $opaque_checkpoint" "- safe_summary: $safe_summary" "- redacted_integrity: $redacted_integrity"; [[ -z $token_count ]] || printf '%s\n' "- token_count: $token_count"; [[ -z $cost ]] || printf '%s\n' "- cost: $cost"; }
comments() { gh api --method GET "repos/$repository/issues/$issue_number/comments" --paginate 2>/dev/null || safe_failure; }
validate_active_body() { local body=$1 key value; [[ $body == *"$marker"* && $body == *'## Issue Agent Run State (v1)'* ]] || return 1; for key in run_id started_at updated_at current_state state_before_stop resume_state role model outcome review_return_count test_summary branch commit draft_pr head_sha ci_summary stop_or_wait_reason opaque_checkpoint safe_summary redacted_integrity; do value=$(sed -n "s/^- $key: //p" <<<"$body"); [[ $(grep -c "^- $key: " <<<"$body") == 1 && -n $value ]] || return 1; case $key in run_id) run "$value";; started_at|updated_at) timestamp "$value";; current_state|state_before_stop|resume_state) state "$value";; role) [[ $value =~ ^[A-Za-z][A-Za-z_-]{1,63}$ ]];; model) [[ $value =~ ^[A-Za-z0-9._:-]{1,127}$ ]];; outcome) [[ $value =~ ^[A-Z][A-Z_]{1,63}$ ]];; review_return_count) [[ $value =~ ^[0-9]+$ ]];; test_summary|ci_summary|stop_or_wait_reason|safe_summary) safe_text "$value";; branch) branch_value "$value";; commit|head_sha) sha_value "$value";; draft_pr) pr_value "$value";; opaque_checkpoint|redacted_integrity) opaque "$value";; esac || return 1; done; for key in token_count cost; do value=$(sed -n "s/^- $key: //p" <<<"$body"); [[ $(grep -c "^- $key: " <<<"$body") -le 1 ]] || return 1; [[ -z $value || ( $key == token_count && $value =~ ^[0-9]+$ ) || ( $key == cost && $value =~ ^[0-9]+([.][0-9]+)?$ ) ]] || return 1; done; }
active_record() { local rows row id encoded body active_run; rows=$(comments | jq -r -s --arg marker "$marker" 'flatten | .[] | select((.body // "") | contains($marker)) | "\(.id)\t\(.body|@base64)"' 2>/dev/null) || safe_failure; [[ $(grep -c . <<<"$rows" || true) == 1 ]] || safe_failure; row=$rows; id=${row%%$'\t'*}; encoded=${row#*$'\t'}; body=$(printf '%s' "$encoded" | base64 -d 2>/dev/null) || safe_failure; validate_active_body "$body" || safe_failure; active_run=$(sed -n 's/^- run_id: //p' <<<"$body"); printf '%s\t%s\n' "$id" "$active_run"; }
no_active() { local ids; if ! ids=$(comments | jq -r -s --arg marker "$marker" 'flatten | .[] | select((.body // "") | contains($marker)) | .id' 2>/dev/null); then safe_failure; fi; [[ -z $ids ]] || safe_failure; }
post() { gh api --method POST "repos/$repository/issues/$issue_number/comments" -f body="$1" >/dev/null 2>&1 || safe_failure; }; patch() { gh api --method PATCH "repos/$repository/issues/comments/$1" -f body="$2" >/dev/null 2>&1 || safe_failure; }; same_active() { local record=$1 id=$2 expected=$3; [[ ${record%%$'\t'*} == "$id" && ${record#*$'\t'} == "$expected" ]] || safe_failure; }
checkpoint_body() { for public_value in "$event" "$run_id" "$updated_at" "$transition" "$opaque_checkpoint" "$safe_summary" "$redacted_integrity" "$state_before_stop" "$stop_or_wait_reason" "$resume_state" "$old_state" "$discard_reason"; do credential_free "$public_value" || safe_failure; done; [[ $event =~ ^(BLOCKED|RESUMED|APPROVED|PUBLISHED|DISCARDED)$ ]] && transition_value "$transition" && run "$run_id" && timestamp "$updated_at" && opaque "$opaque_checkpoint" && opaque "$redacted_integrity" && safe_text "$safe_summary" || safe_failure; case $event in BLOCKED) state "$state_before_stop" && [[ $state_before_stop != unset ]] && safe_text "$stop_or_wait_reason" && [[ $stop_or_wait_reason != unset ]] || safe_failure;; RESUMED) state "$resume_state" && [[ $resume_state != unset ]] || safe_failure;; DISCARDED) state "$old_state" && [[ $old_state != unset ]] && safe_text "$discard_reason" && [[ $discard_reason != unset ]] || safe_failure;; esac; printf '%s\n' '## Issue Agent Run Checkpoint (v1)' "- event: $event" "- run_id: $run_id" "- occurred_at: $updated_at" "- transition: $transition" "- opaque_checkpoint: $opaque_checkpoint" "- safe_summary: $safe_summary" "- redacted_integrity: $redacted_integrity"; [[ $event != BLOCKED ]] || printf '%s\n' "- state_before_stop: $state_before_stop" "- stop_or_wait_reason: $stop_or_wait_reason"; [[ $event != RESUMED ]] || printf '%s\n' "- resume_state: $resume_state"; [[ $event != DISCARDED ]] || printf '%s\n' "- old_state: $old_state" "- discard_reason: $discard_reason"; }
case $operation in
  active-create) body=$(active_body); no_active; post "$body"; active_record >/dev/null;;
  active-update) body=$(active_body); before=$(active_record); same_active "$before" "${before%%$'\t'*}" "$run_id"; patch "${before%%$'\t'*}" "$body"; same_active "$(active_record)" "${before%%$'\t'*}" "$run_id";;
  checkpoint) body=$(checkpoint_body); before=$(active_record); same_active "$before" "${before%%$'\t'*}" "$run_id"; post "$body"; same_active "$(active_record)" "${before%%$'\t'*}" "$run_id";;
  switch) body=$(active_body); [[ $old_run_id != "$run_id" ]] && run "$old_run_id" && state "$old_state" && [[ $old_state != unset ]] && safe_text "$old_safe_summary" && transition_value "$old_transition" && opaque "$old_opaque_checkpoint" && opaque "$old_redacted_integrity" && safe_text "$discard_reason" && [[ $discard_reason != unset ]] || safe_failure; old_body=$(event=DISCARDED run_id=$old_run_id opaque_checkpoint=$old_opaque_checkpoint redacted_integrity=$old_redacted_integrity safe_summary=$old_safe_summary transition=$old_transition checkpoint_body); before=$(active_record); same_active "$before" "${before%%$'\t'*}" "$old_run_id"; post "$old_body"; patch "${before%%$'\t'*}" "$body"; same_active "$(active_record)" "${before%%$'\t'*}" "$run_id";;
esac
printf '%s\n' '{"outcome":"UPDATED","safe_summary":"public state comment was updated"}'
